version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - devops-task-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - devops-task-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Stack startup
          command: stack build
      - save_cache:
          name: Cache Dependencies
          key: devops-task-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Unit tests
          command: stack test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - store_artifacts:
          # Upload buildresults for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: ~/.local/bin/devops-api
          destination: devops-api
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/devops-task:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/devops-task:$TAG
