version: 2.1
jobs:
  build:
    docker:
      - image: galactica/stack-build-dsiluri:0.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - devops-task-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - devops-task-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Stack startup
          command: stack build
      - save_cache:
          name: Cache Dependencies
          key: devops-task-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
  test:
    docker:
      - image: galactica/stack-build-dsiluri:0.1
    steps:
      - run: stack init
      - run:
          name: Unit tests
          command: stack test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
 
