version: 2.1
jobs:
  build:
    docker:
      - image: galactica/stack-build-dsiluri:0.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - devops-task-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - devops-task-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Stack startup
          command: stack build
      - save_cache:
          name: Cache Dependencies
          key: devops-task-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Exec DevOps Haskell app
          command: stack exec devops-api &
      - run:
          name: Display curl version
          command: curl --version
      - run:
          name: Display stack ps
          command: 'ps -ef|grep stack'
      - run:
          name: Test server
          command: |
            curl -v -X POST http://localhost:3000/api/ -d '{"jsonrpc": "2.0", "id": 0, "method": "get_raw_transactions", "params": { "address": "SOMEADDRESS" } }' -H 'Content-Type: application/json' -u user:pass
 
