version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - run:
          name: Stack startup
          command: stack build
      - run:
          name: Exec DevOps Haskell app
          command: stack exec devops-api &
