version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - run:
          name: Start Stack server
          command: stack start
      - run:
          name: Exec DevOps Haskell app
          command: stack exec devops-api
      #- run:
      #    name: Display Stack version
      #    command: stack --version
      #- run:
      #    name: Execute Stack test
      #    command: stack test
