version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - run:
          name: Stack startup
          command: stack build
      - run:
          name: Exec DevOps Haskell app
          command: stack exec devops-api &
      - run:
          name: Server test
          command: |
            curl -v -X POST http://localhost:3000/api/ -d '{"jsonrpc": "2.0", "id": 0, "method": "get_raw_transactions", "params": { "address": "SOMEADDRESS" } }' -H 'Content-Type: application/json' -u user:pass
