version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Execute Stack test
          command: stack --no-terminal test -j1
      - run:
          name: Stack startup
          command: stack build
      - run:
          name: Exec DevOps Haskell app
          command: stack exec devops-api
      #- run:
      #    name: Display Stack version
      #    command: stack --version

